<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Zenit.Share\Zenit.Share.Data\Zenit.Share.Data.csproj" />
    <ProjectReference Include="..\..\Zenit.Share\Zenit.Share.Business\Zenit.Share.Business.csproj" />
    <ProjectReference Include="..\..\Zenit.Share\Zenit.Share.Host\Zenit.Share.Host.csproj" />
    <ProjectReference Include="..\Zenit.Statistics.Data\Zenit.Statistics.Data.csproj" />
    <ProjectReference Include="..\Zenit.Statistics.Common\Zenit.Statistics.Common.csproj" />
    <ProjectReference Include="..\Zenit.Statistics.Contract\Zenit.Statistics.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

</Project>
